### ISSUE TITLE
Feature request: Port code to Python or R

### ISSUE THREAD

**Issue by LukeAFullard** [jbogalo/CiSSA#1]
Is it possible to port this package to Python or R?
Thank you

**Comment by jbogalo** [comment]
Good morning.

 

Thank you very much for your interest in CiSSA. It is possible to port the CiSSA package to another language, but that is already the task of the interested researcher.

 

Best regards,

Juan Bógalo

 

De: LukeAFullard ***@***.***> 
Enviado el: lunes, 24 de octubre de 2022 3:28
Para: jbogalo/CiSSA ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [jbogalo/CiSSA] Feature request (Issue #1)

 

Is it possible to port this package to Python or R?
Thank you

**Comment by LukeAFullard** [comment]
I will do this and keep you updated with my progress

**Comment by LukeAFullard** [comment]
Hi, I thought you may be interested to know that I have published my Python code for CiSSA on github.
https://github.com/LukeAFullard/pyCiSSA

It is a very close replica of your Matlab code, but I still need to add documentation.

I also add an extra function so the case I = a cell array (or in Python, a dictionary). Like your case 1 we can pre-define period grouping (usually years) and also export the noise.
The Python dictionary structure also allows us to name the groupings in the code which is nice.

Anyway, I hope to develop more of CiSSA, it is very cool, thank you!

**Comment by jbogalo** [comment]
Hello.

 

Again, thank you for your interest in CiSSA. I am very happy with the publication of CiSSA in Python that you have made. I hope it will be very useful.

 

Juan Bógalo

 

 

De: LukeAFullard ***@***.***> 
Enviado el: sábado, 29 de octubre de 2022 12:33
Para: jbogalo/CiSSA ***@***.***>
CC: jbogalo ***@***.***>; Comment ***@***.***>
Asunto: Re: [jbogalo/CiSSA] Feature request: Port code to Python or R (Issue #1)

 

Hi, I thought you may be interested to know that I have published my Python code for CiSSA on github.
https://github.com/LukeAFullard/pyCiSSA

It is a very close replica of your Matlab code, but I still need to add documentation.

I also add an extra function so the case I = a cell array (or in Python, a dictionary). Like your case 1 we can pre-define period grouping (usually years) and also export the noise.
The Python dictionary structure also allows us to name the groupings in the code which is nice.

Anyway, I hope to develop more of CiSSA, it is very cool, thank you!
